### ISSUE TITLE
Dark theme attribute is hard-coded in tooltip overlay

### ISSUE THREAD

**Issue by juuso-vaadin** [vaadin-component-factory/vcf-tooltip#3]
Allow configuring the dark theme variant on overlay to ease implementing a custom theme.

As workaround the theme attribute can currently be removed in Java with
`tooltip.getElement().executeJs("this.shadowRoot.querySelector('[part=content]').removeAttribute('theme')");`

**Comment by TatuLund** [comment]
Re-styling will require something more than just removal of the dark theme, see the result. 

![image](https://user-images.githubusercontent.com/14309836/97976822-e4458b80-1dd3-11eb-936a-f17183e7e4ba.png)

However in version 1.3.3 minor change was introduced, dark theme is set only if not theme defined, hence above JavaScript is not needed anymore

https://github.com/vaadin-component-factory/vcf-tooltip/blob/polymer-3/src/vcf-tooltip.js#L199

**Comment by TatuLund** [comment]
Fixed in version 1.3.4
