### ISSUE TITLE
[polymer-3]: Fixed polymer dependency causes duplicate resolution

### ISSUE THREAD

**Issue by tpluscode** [vaadin-component-factory/vcf-tooltip#7]
Please change the dependency on `@polymer/polymer` to be a range. Otherwise I can easily end up with multiple copies of Polymer in build and `Cannot define multiple custom elements with the same tag name` errors at runtime

**Comment by jcgueriaud1** [comment]
Sorry for the late answer.
v1.3.14 depends on polymer ˆ3.2.0, it should help to avoid conflicts
