### ISSUE TITLE
Tooltip not showing in reopen Dialog

### ISSUE THREAD

**Issue by AntKerf** [vaadin-component-factory/vcf-tooltip#9]
If you create a tooltip in a form inherited from Dialog, then after reopening the form, the tooltip does not work.

In this example, upon creation, the form opens in the constructor, Tooltip works, but if you close the dialog and open it again via the button, the tooltip stops working.

i use: vaadin.version:14.3.3, tooltip.version:1.3.5, Google Chrome:90.0.4430.212

````
@Route(value = "Future", layout = MainLayout.class)
@RouteAlias(value = "/Future", layout = MainLayout.class)
public class FutureView extends VerticalLayout {

	BaseForm form;
	public FutureView() {
                this.setSizeFull();
		form = new BaseForm();
		form.open();
		
		Button btn = new Button("Open form");
		btn.addClickListener(e->form.open());
		
		add(btn,form);
	}
}

class BaseForm extends Dialog {
	Tooltip tooltip;
	TextField text;
	
    public BaseForm() {
        text= new TextField();
        text.setReadOnly(true);
    
        tooltip= new Tooltip();
        tooltip.attachToComponent(text);
        tooltip.add(new Span("Some"));
        add(text,tooltip);
    }
}
````

**Comment by jcgueriaud1** [comment]
Yes, there is an open issue here: https://github.com/vaadin-component-factory/tooltip/issues/13
I'm adding the example in the other ticket and close this one.
